### ISSUE TITLE
Version 0.9 garbles API-output on :8080 vs version 0.8

### ISSUE THREAD

**Issue by agerhard0** [volkszaehler/mbmd#106]
Data output on :8080 is not ok with version 0.9, although itwas with 0.8 (s. att).

![Bildschirmfoto von 2020-04-01 23-02-19](https://user-images.githubusercontent.com/45701116/78187359-8da75600-746e-11ea-9334-03cc2a956757.png)

Reference:
https://www.photovoltaikforum.com/thread/134974-mbmd-neues-werkzeug-zum-auslesen-von-wechselrichtern-und-z%C3%A4hlern/?postID=1968266#post1968266

**Comment by andig** [comment]
Fixed: https://github.com/volkszaehler/mbmd/releases/tag/0.9.1

**Comment by agerhard0** [comment]
Replacing 0.8 with 0.9.1 (incl. stopping/starting system service) does not solve the issue. Result is still  garbled output data on :8080. Going back to 0.8 solves this issue again.

**Comment by andig** [comment]
Please make sure to force-reload the web page to refresh the javascripts. If in doubt, clear browser cache.

**Comment by agerhard0** [comment]
Clearing browser cache did the trick. 0.9.1 output on :8080 is fine here now.
